module.exports = Object.freeze({
  PLAYER_BASE_RADIUS: 10,
  ELECTRON_RADIUS: 3,
  PROTON_RADIUS: 9,
  NEUTRON_RADIUS: 9,

  PLAYER_BASE_SPEED: 400,
  ELECTRON_MAX_SPEED: 500,
  PROTON_MAX_SPEED: 100,
  NEUTRON_MAX_SPEED: 50,

  SCORE_ELECTRON_CATCH: 10,
  SCORE_PROTON_CATCH: 5,
  SCORE_NEUTRON_CATCH: 3,

  ELECTRONS_MAX_COUNT: 50,
  PROTONS_MAX_COUNT: 20,
  NEUTRONS_MAX_COUNT: 15,

  MAP_SIZE: 3000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
  },
});
